stages:
  - build
  - test
  - test_hardware
  - deploy

.hdl_tests:
    tags:
     - vivado
     - matlab
    stage: test
    dependencies:
     - build:2018_R2
    artifacts:
        when: always
        name: "$CI_COMMIT_REF_NAME"
        paths:
            - test/logs/
            - Report.pdf
        reports:
            junit: test/BSPTestResults.xml


# Default build
build:2018_R2:
    tags:
     - vivado
     - matlab
    stage: build
    script:
     - export MLRELEASE=R2019a
     - ./CI/scripts/dockermake build
     - ./CI/scripts/dockermake add_libad9361
     - ./CI/scripts/dockermake gen_tlbx
     - mkdir mltbx
     - ls *.mltbx
     - cp *.mltbx mltbx/
    artifacts:
        paths:
            - hdl_wa_bsp/
            - mltbx/
            - deps/

# Future branches
build:master:
    tags:
     - vivado
     - matlab
    stage: build
    script:
     - export HDLBRANCH=hdl_2018_r2
     - export MLRELEASE=R2019a
     - ./CI/scripts/dockermake build
     - export HDLBRANCH=
     - export MLRELEASE=
    allow_failure: true
    artifacts:
        paths:
            - hdl_wa_bsp/

# Test HWA no install zed
test:2018_R2_ZED:
    extends: .hdl_tests
    script:
     - export MLRELEASE=R2019a
     - export BOARD=zed
     - ./CI/scripts/dockermake test

# Test HWA no install zc702
test:2018_R2_ZC702:
    extends: .hdl_tests
    script:
     - export MLRELEASE=R2019a
     - export BOARD=zc702
     - ./CI/scripts/dockermake test

# Test HWA no install zc706
test:2018_R2_ZC706:
    extends: .hdl_tests
    script:
     - export MLRELEASE=R2019a
     - export BOARD=zc706
     - ./CI/scripts/dockermake test

# Test HWA no install zcu102
test:2018_R2_ZCU102:
    extends: .hdl_tests
    script:
     - export MLRELEASE=R2019a
     - export BOARD=zcu102
     - ./CI/scripts/dockermake test

# Test HWA no install adrv9361
test:2018_R2_ADRV9361:
    extends: .hdl_tests
    script:
     - export MLRELEASE=R2019a
     - export BOARD=adrv9361
     - ./CI/scripts/dockermake test

# Test HWA no install adrv9364
test:2018_R2_ADRV9364:
    extends: .hdl_tests
    script:
     - export MLRELEASE=R2019a
     - export BOARD=adrv9364
     - ./CI/scripts/dockermake test

# Test HWA with install
test_installer:2018_R2_Installer:
    extends: .hdl_tests
    script:
     - export MLRELEASE=R2019a
     - cp mltbx/* .
     - pwd
     - ls
     - ls *.mltbx
     - ./CI/scripts/dockermake test_installer
    artifacts:
        when: always
        paths:
            - mltbx/
            - zip/
            - test/logs/
        reports:
            junit: test/BSPTestResults.xml

# Test weekly fully sythesized design
test:Synthesize:
    when: manual
    extends: .hdl_tests
    script:
     - ./CI/scripts/dockermake test_synth

# Test targeting demos (no hardware)
test:targeting_demos:
    tags:
     - matlab
     - vivado
    stage: test
    dependencies:
     - build:2018_R2
    script:
     - export MLRELEASE=R2019a
     - ./CI/scripts/dockermake test_targeting_demos
    artifacts:
        when: always
        name: "$CI_COMMIT_REF_NAME"
        paths:
            - test/
            - Report.pdf

# Test streaming interfaces with hardware
test_hardware:Streaming_Hardware:
    tags:
     - matlab
     - hardware
    stage: test_hardware
    dependencies:
     - build:2018_R2
    script:
     - export MLRELEASE=R2019a
     - cd CI/scripts
     - make test_streaming
    artifacts:
        paths:
            - logs/
            - Report.pdf

# Test EVM performance with hardware
test_hardware:EVM_Hardware:
    only:
     - schedules
    tags:
     - matlab
     - hardware
    stage: test_hardware
    dependencies:
     - build:2018_R2
    script:
     - export MLRELEASE=R2019a
     - cd CI/scripts
     - make test_evm
    artifacts:
        paths:
            - logs/
            - Report.pdf

# Deploy
deploy:
    tags:
     - matlab
    stage: deploy
    dependencies:
     - test_installer:2018_R2_Installer
    script:
     - echo "Complete"
    artifacts:
        paths:
            - mltbx/

